sport/Controllers/AllQueriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using sport.Classes;
using sport.Models;
using System.Data.SqlClient;
namespace sport.Controllers
{
    public class AllQueriesController : Controller
    {
        // GET: AllQueries
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Query1(string name, string name1)
        {
            List<Query1Data> result;
            using (var db = new sportEntities())
            {
                //  SqlCommand command = new SqlCommand();
                // SqlParameter nameParam = new SqlParameter("name", name);

                //SqlParameter name1Param = new SqlParameter("name1", name1);
                
                var param = new SqlParameter("@name", name)
                {
                    SqlDbType = System.Data.SqlDbType.Text
                };
                


                string sql = @"SELECT c.rank, p.result, s.surname, se.section_name
                    FROM Participation p JOIN Competition c
                    ON p.p_сompetition_ID = c.сompetition_ID
                    JOIN Sportsman s
                    ON p.p_sportsman_ID = s.sportsman_ID
                    JOIN Section se
                    ON s.s_section_ID = se.section_ID
                    WHERE se.section_name = '@name' ";
                result = db.Database.SqlQuery<Query1Data>(sql, name).ToList();
            }

            TempData["result"] = result;

            return RedirectToAction("Query1Result");
        }
        [HttpPost]
        public ActionResult Query2(string name2)
        {
            List<Query2Data> result;
            using (var db = new sportEntities())
            {
              /*  var param3 = new SqlParameter("@name2", name2)
                {
                    SqlDbType = System.Data.SqlDbType.Text

                };*/
                string sql = @"SELECT   s.surname AS [Спортсмен], AVG(s.age) AS [Возраст]
                FROM Participation p JOIN Competition c
                ON p.p_сompetition_ID = c.сompetition_ID
                JOIN Sportsman s
                ON p.p_sportsman_ID = s.sportsman_ID
                JOIN Section se
                ON s.s_section_ID = se.section_ID
                
                GROUP BY s.surname";
                result = db.Database.SqlQuery<Query2Data>(sql).ToList();
            }

            TempData["result"] = result;

            return RedirectToAction("Query2Result");
        }
        [HttpPost]
        public ActionResult Query3(string letter)
        {
            List<Query3Data> result;
            using (var db = new sportEntities())
            {
                string sql = @"SELECT        Section.section_name, Competition.date_competition, Sportsman.surname, Sportsman.age, Participation.place
                            FROM            Competition INNER JOIN
                         Participation ON Competition.сompetition_ID = Participation.p_сompetition_ID INNER JOIN
                         Sportsman ON Participation.p_sportsman_ID = Sportsman.sportsman_ID INNER JOIN
                         Section ON Sportsman.s_section_ID = Section.section_ID
                        WHERE        (Section.section_name = '') AND (Competition.date_competition = '') AND (Participation.place = '')";
                result = db.Database.SqlQuery<Query3Data>(sql).ToList();
            }

            TempData["result"] = result;

            return RedirectToAction("Query3Result");
        }
        [HttpPost]
        public ActionResult Query4()
        {
            List<Query4Data> result;
            using (var db = new sportEntities())
            {/*
                var param5 = new SqlParameter("@name3", name3)
                {
                    SqlDbType = System.Data.SqlDbType.Text

                };
                var param6 = new SqlParameter("@name4", name4)
                {
                    SqlDbType = System.Data.SqlDbType.Text

                };*/
                string sql = @"SELECT COUNT(sp.sportsman_ID) FROM Sportsman sp
                    JOIN Section sec ON sp.s_section_ID = sec.section_ID
                    JOIN Participation p ON sp.sportsman_ID = p.p_sportsman_ID
                    JOIN Competition c ON c.сompetition_ID = p.p_сompetition_ID
                    WHERE c.rank  AND sec.section_name ";
                result = db.Database.SqlQuery<Query4Data>(sql).ToList();


                TempData["result"] = result;
            }

            return RedirectToAction("Query4Result");
        }
        public ActionResult Query1Result()
        {
            TempData.Keep();
            return View(TempData["result"]);
        }
        public ActionResult Query2Result()
        {
            TempData.Keep();
            return View(TempData["result"]);
        }
        public ActionResult Query3Result()
        {
            TempData.Keep();
            return View(TempData["result"]);
        }
        public ActionResult Query4Result()
        {
            TempData.Keep();
            return View(TempData["result"]);
        }



    }
}

sport/Views/AllQueries/Index.cshtml
@{
    ViewBag.Title = "Запросы";
}
@using (Html.BeginForm("Query1", "AllQueries", FormMethod.Post))
{
    <h3>Запрос 1</h3>
    <p>Вывести информацию о призерах <input type="text" required name="name" /> чемпионата по </p>
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Выполнить" class="btn btn-default" />
        </div>
    </div>
}
<br>
<hr />
@using (Html.BeginForm("Query2", "AllQueries", FormMethod.Post))
{
    <h3>Запрос 2</h3>
    <p>Определить средний возраст спортсменов секции , участвовавшие хотя бы в одном соревновании </p>
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Выполнить" class="btn btn-default" />
        </div>
    </div>
}
<br>
<hr />
@using (Html.BeginForm("Query3", "AllQueries", FormMethod.Post))
{
    <h3>Запрос 3</h3>
    <p>Вывести информацию о спортсмене, занявшего <input type="text" /> место на городском чемпионате  <input type="date" required name="date1" />. По <input type="text" /> </p>
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Выполнить" class="btn btn-default" />
        </div>
    </div>
}
<br>
<hr />
@using (Html.BeginForm("Query4", "AllQueries", FormMethod.Post))
{
    <h3>Запрос 4</h3>
    <p>Определить число членов секции легкая атлетика, участвовавшие в городском чемпионате </p>
    @Html.AntiForgeryToken()
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Выполнить" class="btn btn-default" />
        </div>
    </div>
}
<br>
<hr />

sport/Views/AllQueries/Query1Result.cshtml
@model IEnumerable<sport.Classes.Query1Data>
@{
    ViewBag.Title = "Результаты запроса";
}
<table class="table table-bordered table-hover">
    <tr>
        <th>
            Ранг соревнования
        </th>
        <th>
            Результат
        </th>
        <th>
            Фамилия спортсмена
        </th>
        <th>
            Название секции
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.rank
            </td>
            <td>
                @item.result
            </td>
            <td>
                @item.surname
            </td>
            <td>
                @item.section_name
            </td>
       </tr>
    }
</table>

sport/Views/AllQueries/Query2Result.cshtml
@model IEnumerable<sport.Classes.Query2Data>
@{
    ViewBag.Title = "Результаты запроса";
}

<table class="table table-bordered table-hover">
    <tr>
        <th>
            ФИО
        </th>
        <th>
            Возраст
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.surname
            </td>
            <td>
                @item.avg
            </td>

        </tr>
    }
</table>

sport/Views/AllQueries/Query3Result.cshtml
@model IEnumerable<sport.Classes.Query3Data>
@{
    ViewBag.Title = "Результаты запроса";
}
<h2>@ViewBag.Title</h2>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            Название секции
        </th>
        <th>
            Фамилия спортсмена
        </th>
        <th>
            Возраст
        </th>
        <th>
            Дата соревнования
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.section_name
            </td>
            <td>
                @item.surname
            </td>
            <td>
                @item.age

            </td>
            <td>
                @item.data_competition
            </td>

        </tr>
    }
</table>

sport/Views/AllQueries/Query4Result.cshtml
@model IEnumerable<sport.Classes.Query4Data>
@{
    ViewBag.Title = "Результаты запроса";
}
<h2>@ViewBag.Title</h2>
<table class="table table-bordered table-hover">
    <tr>
        <th>
            Число участников
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.sportsman_id
            </td>

        </tr>
    }
</table>